-- supabase.sql
-- Ejecutar en Supabase > SQL Editor

create sequence if not exists cotizacion_numero_seq start 1 increment 1;

create table if not exists public.cotizaciones (
  id bigint generated by default as identity primary key,
  numero text not null unique default (
    'COT-' || lpad(nextval('cotizacion_numero_seq')::text, 6, '0')
  ),
  fecha date not null default current_date,
  cliente text not null default '',
  telefono text not null default '',
  direccion text not null default '',
  vendedor text not null default '',
  observacion text not null default '',
  dias_validez integer not null default 15,
  subtotal numeric(14,2) not null default 0,
  iva numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cotizacion_detalles (
  id bigint generated by default as identity primary key,
  cotizacion_id bigint not null references public.cotizaciones(id) on delete cascade,
  descripcion text not null default '',
  cantidad numeric(14,2) not null default 1,
  precio_unitario numeric(14,2) not null default 0,
  descuento numeric(14,2) not null default 0,
  aplica_iva boolean not null default true,
  total numeric(14,2) not null default 0
);

create index if not exists idx_cotizaciones_numero on public.cotizaciones(numero);
create index if not exists idx_cotizaciones_fecha on public.cotizaciones(fecha);
create index if not exists idx_cotizaciones_cliente on public.cotizaciones(cliente);
create index if not exists idx_detalles_cotizacion on public.cotizacion_detalles(cotizacion_id);

create or replace function public.actualizar_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_cotizaciones_updated_at on public.cotizaciones;
create trigger trg_cotizaciones_updated_at
before update on public.cotizaciones
for each row execute function public.actualizar_updated_at();

alter table public.cotizaciones enable row level security;
alter table public.cotizacion_detalles enable row level security;

drop policy if exists "cotizaciones_select" on public.cotizaciones;
drop policy if exists "cotizaciones_insert" on public.cotizaciones;
drop policy if exists "cotizaciones_update" on public.cotizaciones;
drop policy if exists "cotizaciones_delete" on public.cotizaciones;
drop policy if exists "detalles_select" on public.cotizacion_detalles;
drop policy if exists "detalles_insert" on public.cotizacion_detalles;
drop policy if exists "detalles_update" on public.cotizacion_detalles;
drop policy if exists "detalles_delete" on public.cotizacion_detalles;

create policy "cotizaciones_select" on public.cotizaciones for select to anon, authenticated using (true);
create policy "cotizaciones_insert" on public.cotizaciones for insert to anon, authenticated with check (true);
create policy "cotizaciones_update" on public.cotizaciones for update to anon, authenticated using (true) with check (true);
create policy "cotizaciones_delete" on public.cotizaciones for delete to anon, authenticated using (true);

create policy "detalles_select" on public.cotizacion_detalles for select to anon, authenticated using (true);
create policy "detalles_insert" on public.cotizacion_detalles for insert to anon, authenticated with check (true);
create policy "detalles_update" on public.cotizacion_detalles for update to anon, authenticated using (true) with check (true);
create policy "detalles_delete" on public.cotizacion_detalles for delete to anon, authenticated using (true);


-- =========================================================
-- FICHAS TÉCNICAS
-- (se entregan al cliente como respaldo del trabajo realizado)
-- =========================================================

create sequence if not exists ficha_numero_seq start 1 increment 1;

create table if not exists public.fichas_tecnicas (
  id bigint generated by default as identity primary key,
  numero text not null unique default (
    'FT-' || lpad(nextval('ficha_numero_seq')::text, 6, '0')
  ),
  fecha date not null default current_date,

  -- Datos del cliente
  cliente text not null default '',
  cliente_cedula text not null default '',
  telefono text not null default '',
  direccion text not null default '',
  contacto text not null default '',
  tecnico text not null default '',
  activo text not null default '',
  persona_cargo text not null default '',
  referencia text not null default '',

  -- Datos del equipo
  marca text not null default '',
  modelo text not null default '',
  tipo_equipo text not null default '',
  capacidad_btu text not null default '',
  instalacion boolean not null default false,
  mant_preventivo boolean not null default false,
  mant_correctivo boolean not null default false,
  tiempo_garantia text not null default '',
  tipo_refrigerante text not null default '',
  voltaje text not null default '',
  amperaje text not null default '',
  lectura_antes text not null default '',
  lectura_despues text not null default '',

  -- Detalle del servicio
  ubicacion_equipo text not null default '',
  materiales_utilizados text not null default '',
  observaciones text not null default '',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Si ya habías ejecutado la versión anterior de este script (con horas de
-- entrada/salida), esta línea las quita sin afectar el resto de los datos:
alter table public.fichas_tecnicas drop column if exists hora_entrada;
alter table public.fichas_tecnicas drop column if exists hora_salida;

create index if not exists idx_fichas_numero on public.fichas_tecnicas(numero);
create index if not exists idx_fichas_fecha on public.fichas_tecnicas(fecha);
create index if not exists idx_fichas_cliente on public.fichas_tecnicas(cliente);
create index if not exists idx_fichas_tecnico on public.fichas_tecnicas(tecnico);

-- Reutiliza la misma función de public.actualizar_updated_at() creada arriba
drop trigger if exists trg_fichas_updated_at on public.fichas_tecnicas;
create trigger trg_fichas_updated_at
before update on public.fichas_tecnicas
for each row execute function public.actualizar_updated_at();

alter table public.fichas_tecnicas enable row level security;

drop policy if exists "fichas_select" on public.fichas_tecnicas;
drop policy if exists "fichas_insert" on public.fichas_tecnicas;
drop policy if exists "fichas_update" on public.fichas_tecnicas;
drop policy if exists "fichas_delete" on public.fichas_tecnicas;

create policy "fichas_select" on public.fichas_tecnicas for select to anon, authenticated using (true);
create policy "fichas_insert" on public.fichas_tecnicas for insert to anon, authenticated with check (true);
create policy "fichas_update" on public.fichas_tecnicas for update to anon, authenticated using (true) with check (true);
create policy "fichas_delete" on public.fichas_tecnicas for delete to anon, authenticated using (true);
